name: Test and Create badge to branch coverage
run-name: Test and Create badge to branch coverage
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 21.7.1

      - name: Install Dependencies
        run: npm install
  
      - name: Run Tests
        run: npm run test

      - name: Generating coverage badges
        uses: jpb06/jest-badges-action@latest
        with:
          branches: 'main'
    